### ISSUE TITLE
How do I clean up after a scenario is run?

### ISSUE THREAD

**Issue by eodolphi** [albertjan/ember-cli-yadda#47]
In some of our steps we do stuff that needs to be cleaned up after a scenario has run (stubbing things for example). Preferably I would not like to add a "Then I clean everything up" step to the end of all our scenarios.

Is there a way let a step run something after a scenario finished so that the step can clean up after itself?

**Comment by ArtemAlagizov** [comment]
would also very much like to know that

**Comment by albertjan** [comment]
Yadda doesn't provide something like that as far as I can see. Ember destroys the entire app every feature, so it might be an idea to break out the scenario's and steps into separate features, we might want to move the destroy app to a scenario level, or make it a setting. It will make the tests slower though.

**Comment by lolmaus** [comment]
Hey @eodolphi and @ArtemAlagizov, not that though a single app instance is shared it does get properly reset for me. E. g. Mirage records do not leak across scenarios.

**Comment by eodolphi** [comment]
Hi @lolmaus You are right, mirage is properly reset.

 I also have some other things that get set up at the beginning of the test, such as stubbing redirects for example. I would like to reset those too. But I cannot figure out a way to do that cleanly.

**Comment by simonihmig** [comment]
For acceptance tests you could put such things into your `start-app.js`/`destroy-app.js`, although that is certainly not the most clean way...

I am in the process of refactoring a large test suite to the new RFC268 based testing APIs (which `ember-cli-yadda` does not support yet), as part of that will try to put some additional PRs together. First I implemented some hard-coded support, but just today realized that a better way might be to allow a hook to customize the setup of your tests. This would allow you to call the test frameworks `beforeEach`/`afterEach` to setup/teardown whatever you need. So stay tuned... ;)

FWIW, for RFC268 based test, Mirage will probably (once https://github.com/samselikoff/ember-cli-mirage/pull/1263 is merged) expect you to call `setupMirage()` in your tests (which will call `beforeEach`/`afterEach`), so some solution is definitely needed.
