### ISSUE TITLE
Put link to original Yadda docs

### ISSUE THREAD

**Issue by BitBrit** [albertjan/ember-cli-yadda#51]
Some people get to your library when they search for BDD in Ember. Those people don't/might not know of the actual Yadda library (https://github.com/acuminous/yadda). As your current documentation is really just a supplement to the original Yadda docs, please put a link to those docs on your page.

**Comment by albertjan** [comment]
Good one will do 👍

**Comment by albertjan** [comment]
Addressed in #71
