### ISSUE TITLE
Error in an async step is not reported to QUnit, test hangs

### ISSUE THREAD

**Issue by lolmaus** [albertjan/ember-cli-yadda#62]
Consider this step:

```js
.then("should not crash", async function () {
  throw new Error("Oops, it crashed");
})
```

For me, it results in QUnit hanging and timing out. The error is visible in console as "uncaught error in promise", but not in QUnit output.

Likely an issue upstream. I tried to follow Yadda codebase from [here](https://github.com/acuminous/yadda/blob/v1.4.0/lib/Macro.js#L42) and got lost in callbacks.

**Comment by lolmaus** [comment]
Reported upstream: https://github.com/acuminous/yadda/issues/235

Feel free to close this if you are certain this can't be resolved in the addon.

**Comment by lolmaus** [comment]
I've traced the problem to this line: https://github.com/albertjan/ember-cli-yadda/blob/master/lib/test-runner/qunit/acceptance.js#L29

**Comment by lolmaus** [comment]
OK, I got it. Will post a PR.

**Comment by albertjan** [comment]
Thanks!
