### ISSUE TITLE
semantic versioning in 0.2.3 update

### ISSUE THREAD

**Issue by CezaryH** [albertjan/ember-cli-yadda#67]
Hey, 
please use semantic versioning, as your change in 0.2.3 update broke mine projects.
You added new file that is required. I know it's in blueprint, but with automated builds( use npm install ) won't fire blueprint. 

That way adding new required file is breaking change so it should be change to 0.3.0.

Thanks

**Comment by albertjan** [comment]
You’re right sorry about that. We’ll try to do better in the future.
