### ISSUE TITLE
QUnit's "No try/catch" option doesn't work with async steps

### ISSUE THREAD

**Issue by lolmaus** [albertjan/ember-cli-yadda#68]
Normally, enabling the "No try/catch" option in QUnit makes errors fall through into the browser console.

With async steps (either `async function` or simply returning a promise from a step) this does not happen. Debugging becomes tedious: every time I have to copy line number from QUnit reporter, open the relevant file and search for the line number.

**Comment by sfbwalder** [comment]
@lolmaus I think I see what you mean.  When ever an error occurs in the steps js, the error in the console points to `rsvp.js:27`.  The stack trace in console error takes you to the right line in tests.js, but not to the line in the steps js that failed.

Comparing that to when an error occurs in an application test, the error in the console points directly to the line in the steps js that failed.  This makes it quicker to identify the error.

Is this what you are seeing?

**Comment by lolmaus** [comment]
No, it's the matter of whether the error is visible in the browser console. When `No try/catch` is enabled, QUnit normally does not catch the error and lets it fall through.

**Comment by sfbwalder** [comment]
It seems I can't recreate it.  I am using 0.3.0.  When I get an error with "No try/catch", I see something like this in the console:

```
rsvp.js:27 Uncaught TypeError: Cannot read property 'isHidden' of undefined
    at Object._callee2$ (http://localhost:4200/assets/tests.js:1744:54)
    (lines removed)
    at http://localhost:4200/assets/tests.js:1816:15
    at <anonymous>
```

**Comment by lolmaus** [comment]
I've noticed that even without `ember-cli-yadda` some errors don't fall through.

A few days ago I spent hours figuring out a weird error in Ember internals which didn't fall through to the console (without Yadda), and QUnit stacktrace pointed at `<anonymous>` paths:

```
TypeError: Cannot read property '__deprecatedInstance__' of null
    at getOwner (<anonymous>:2375:24)
    at Class.reset (<anonymous>:2316:27)
    at Class.start (<anonymous>:2279:14)
    at appStarted (<anonymous>:8403:38)
    at Class.didBecomeReady (<anonymous>:8478:15)
    at Class.superWrapper [as didBecomeReady] (http://localhost:7357/assets/vendor.js:68596:22)
    at invoke (http://localhost:7357/assets/vendor.js:32154:24)
    at Queue.flush (http://localhost:7357/assets/vendor.js:32033:25)
    at DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:32225:31)
    at Backburner.end (http://localhost:7357/assets/vendor.js:32335:42)
```

I searched through the compiled sources for all instances of `__deprecatedInstance__`, and none of them corresponded to the error.

The error disappeared after restarting the browser. :man_facepalming: 

This indicates that `ember-cli-yadda` has been unfairly accused.

**Comment by artzte** [comment]
Ran into the same issue... found this thread and tried @lolmaus cure of killing and restarting Chrome, and the bizarre error (which was surfacing on subsequent acceptance tests run only in certain test suites). There is something here... we recently went to Qunit 4.3.2. We are using async functions in our production code.

**Comment by lifeart** [comment]
@artzte @lolmaus same issue for
http://localhost:4200/tests?moduleId=70cc73a3&hidepassed
on https://github.com/ember-learn/ember-api-docs/pull/394/files
