### ISSUE TITLE
Could not find module `my-app/tests/helpers/start-app`: support for the new test structure?

### ISSUE THREAD

**Issue by lolmaus** [albertjan/ember-cli-yadda#69]
Trying to use `ember-cli-yadda` in Ember CLI 3.1.0-beta.1, and it fails with error from title.

Note that modern test structure does not have `start-app` and `destroy-app`: http://www.ember-cli-diff.org/?#/v2.18.2/v3.1.0-beta.1

Related RFCs:

* https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md
* https://github.com/emberjs/rfcs/blob/master/text/0268-acceptance-testing-refactor.md

**Comment by simonihmig** [comment]
@lolmaus support for the new testing APIs is under way here: #65. The currently released version does not support it.
